(feat) Fix AS tests (#296)
* (build) Run tests in same version of Ruby as in Gemfile

* (docs) The elastic.co images no longer works

It throws the error

    docker: Error response from daemon: pull access denied for
    docker.elastic.co/elasticsearch, repository does not exist or may require
    'docker login'.

* (fix) Bump hairtrigger to avoid migrations error

Without this, then running migrations would get...

  NoMethodError: undefined method `migrations' for ActiveRecord::Migrator:Class

This is documented at https://github.com/jenseng/hair_trigger/pull/72

* (fix) Avoid Faker error

Without this, then the error

   NameError: uninitialized constant Faker

would occur

* (fix) Rails 5.2 renamed a method

https://guides.rubyonrails.org/5_2_release_notes.html#active-support-notable-changes

(search for secure_compare, which shows its safe for variable length strings)