(fix) Run Elasticsearch migrations to pass more CircleCI tests
There may be a flaky tests which are not addressed in this commit. For example,
sometimes

    rspec ./spec/features/admin_can_reply_to_enquiries_spec.rb:91

Has shown:

    TypeError: undefined is not an object (evaluating 'c[a].dir=c.rtl[a]?"rtl":"ltr"')

Or issues with connecting to localhost with another test:

    Request to 'http://127.0.0.1:2323/admin/opportunities/downloads/new' failed
    to reach server, check DNS and/or server status - Timed out with no open
    resource requests

These tests do pass locally